//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nfebox.domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nfebox.domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://www.portalfiscal.inf.br/nfe&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:include schemaLocation=&quot;leiauteCancNFe_v2.00.xsd&quot;/&gt;
        ///	&lt;xs:element name=&quot;cancNFe&quot; type=&quot;TCancNFe&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Schema XML de validação do Pedido de Cancelamento da Nota Fisca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cancNFe_v2_00 {
            get {
                return ResourceManager.GetString("cancNFe_v2_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://www.portalfiscal.inf.br/nfe&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:include schemaLocation=&quot;leiauteConsultaCadastro_v2.00.xsd&quot;/&gt;
        ///	&lt;xs:element name=&quot;ConsCad&quot; type=&quot;TConsCad&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Schema XML de validação do retorno da consulta cadastr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string consCad_v2_00 {
            get {
                return ResourceManager.GetString("consCad_v2_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://www.portalfiscal.inf.br/nfe&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:include schemaLocation=&quot;leiauteNFe_v2.00.xsd&quot;/&gt;
        ///	&lt;xs:element name=&quot;consReciNFe&quot; type=&quot;TConsReciNFe&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Schema XML de validação do Pedido de Consulta do Recido do  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string consReciNFe_v2_00 {
            get {
                return ResourceManager.GetString("consReciNFe_v2_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot; targetNamespace=&quot;http://www.portalfiscal.inf.br/nfe&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:include schemaLocation=&quot;leiauteConsSitNFe_v2.00.xsd&quot;/&gt;
        ///	&lt;xs:element name=&quot;consSitNFe&quot; type=&quot;TConsSitNFe&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Schema de validação XML dp Pedido de Consulta da Situação Atual da Nota Fiscal Eletrônica&lt;/xs:docume [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string consSitNFe_v2_00 {
            get {
                return ResourceManager.GetString("consSitNFe_v2_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://www.portalfiscal.inf.br/nfe&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:include schemaLocation=&quot;leiauteConsStatServ_v2.00.xsd&quot;/&gt;
        ///	&lt;xs:element name=&quot;consStatServ&quot; type=&quot;TConsStatServ&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Schema XML de validação do Pedido de Consulta do [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string consStatServ_v2_00 {
            get {
                return ResourceManager.GetString("consStatServ_v2_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot; xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; targetNamespace=&quot;http://www.portalfiscal.inf.br/nfe&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:include schemaLocation=&quot;leiauteNFe_v2.00.xsd&quot;/&gt;
        ///	&lt;xs:element name=&quot;enviNFe&quot; type=&quot;TEnviNFe&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Schema XML de validação do Pedido de Concessão de Autorização da No [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string enviNFe_v2_00 {
            get {
                return ResourceManager.GetString("enviNFe_v2_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot; xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; targetNamespace=&quot;http://www.portalfiscal.inf.br/nfe&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:include schemaLocation=&quot;leiauteInutNFe_v2.00.xsd&quot;/&gt;
        ///	&lt;xs:element name=&quot;inutNFe&quot; type=&quot;TInutNFe&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Schema XML de validação do Pedido de Inutilização de Numeração  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string inutNFe_v2_00 {
            get {
                return ResourceManager.GetString("inutNFe_v2_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--  PL_006F versao alteracao do xServ para tornar CANCELAR obrigatorio 21/05/2010 --&gt;
        ///&lt;!--  PL_006c versao com correcoes 24/12/2009 --&gt;
        ///&lt;xs:schema xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://www.portalfiscal.inf.br/nfe&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://www.w3.org/2000/09/xmldsig#&quot; schemaLo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string leiauteCancNFe_v2_00 {
            get {
                return ResourceManager.GetString("leiauteCancNFe_v2_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--  PL_006h versao alteracao no include para leiautteNFe_2.00 10/06/2011                         --&gt;
        ///&lt;!--  PL_006f versao com correcoes no xServ para tornar a literal CONSULTAR obrigatoria 21/05/2010 --&gt;
        ///&lt;!--  PL_006c versao com correcoes 24/12/2009 --&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot; xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; targetNamespace=&quot;http://www.portalfiscal.inf.br/nfe&quot; elementFormDefau [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string leiauteConsSitNFe_v2_00 {
            get {
                return ResourceManager.GetString("leiauteConsSitNFe_v2_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--  PL_006f versao com correcoes no xServ para tornar a literal STATUS obrigatoria 21/05/2010 --&gt;
        ///&lt;xs:schema xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://www.portalfiscal.inf.br/nfe&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:include schemaLocation=&quot;tiposBasico_v1.03.xsd&quot;/&gt;
        ///	&lt;xs:complexType name=&quot;TConsStatServ&quot;&gt;
        ///		&lt;xs:annot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string leiauteConsStatServ_v2_00 {
            get {
                return ResourceManager.GetString("leiauteConsStatServ_v2_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--  PL_006f versao com correcoes no xServ para tornar a literal CONS-CAD obrigatoria 21/05/2010 --&gt;
        ///&lt;!--  PL_006c versao com correcoes 24/12/2009 --&gt;
        ///&lt;xs:schema xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://www.portalfiscal.inf.br/nfe&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:include schemaLocation=&quot;tiposBasico_v1.03.xsd&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string leiauteConsultaCadastro_v2_00 {
            get {
                return ResourceManager.GetString("leiauteConsultaCadastro_v2_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--  PL_006f versao com correcoes no xServ para tornar a literal INUTILIZAR obrigatoria 21/05/2010 --&gt;
        ///&lt;!--  PL_006c versao com correcoes 24/12/2009 --&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot; xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; targetNamespace=&quot;http://www.portalfiscal.inf.br/nfe&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://www.w3.org/2000/09/xm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string leiauteInutNFe_v2_00 {
            get {
                return ResourceManager.GetString("leiauteInutNFe_v2_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--  PL_006j - 20/10/11 - alteracao no formato da placa do veiculo para aceitar AAA999, AAA9999, AA9999 e AAAA999  // NT2011/005 --&gt;
        ///&lt;!--  PL_006i - 03/07/11 - acrescimo do item 6/7 tpEmis  // NT2011/004 --&gt;
        ///&lt;!--  PL_006i - 10/06/11 - acrescimo do item 8 - Venda a Orgao Publico no motDesoICMS  // NT2011/004 --&gt;
        ///&lt;!--  PL_006i - 13/05/11 - correções da NT 2011/004  // v2.0--&gt;
        ///&lt;!--  PL_006g versao com inclusão de novos CFOP e CST do PIS/COFINS 24/06/2010--&gt;
        ///&lt;!--  P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string leiauteNFe_v2_00 {
            get {
                return ResourceManager.GetString("leiauteNFe_v2_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot; targetNamespace=&quot;http://www.portalfiscal.inf.br/nfe&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:include schemaLocation=&quot;leiauteNFe_v2.00.xsd&quot;/&gt;
        ///	&lt;xs:element name=&quot;NFe&quot; type=&quot;TNFe&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Nota Fiscal Eletrônica&lt;/xs:documentation&gt;
        ///		&lt;/xs:annotation&gt;
        ///	&lt;/xs:elemen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nfe_v2_00 {
            get {
                return ResourceManager.GetString("nfe_v2_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot; targetNamespace=&quot;http://www.portalfiscal.inf.br/nfe&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:include schemaLocation=&quot;leiauteCancNFe_v2.00.xsd&quot;/&gt;
        ///	&lt;xs:element name=&quot;procCancNFe&quot; type=&quot;TProcCancNFe&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Pedido de Cancelamento de  NF-e processado&lt;/xs:document [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string procCancNFe_v2_00 {
            get {
                return ResourceManager.GetString("procCancNFe_v2_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot; targetNamespace=&quot;http://www.portalfiscal.inf.br/nfe&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:include schemaLocation=&quot;leiauteInutNFe_v2.00.xsd&quot;/&gt;
        ///	&lt;xs:element name=&quot;ProcInutNFe&quot; type=&quot;TProcInutNFe&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Pedido de inutilização de númeração de  NF-e processado [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string procInutNFe_v2_00 {
            get {
                return ResourceManager.GetString("procInutNFe_v2_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot; targetNamespace=&quot;http://www.portalfiscal.inf.br/nfe&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:include schemaLocation=&quot;leiauteNFe_v2.00.xsd&quot;/&gt;
        ///	&lt;xs:element name=&quot;nfeProc&quot; type=&quot;TNfeProc&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt; NF-e processada&lt;/xs:documentation&gt;
        ///		&lt;/xs:annotation&gt;
        ///	&lt;/xs:elem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string procNFe_v2_00 {
            get {
                return ResourceManager.GetString("procNFe_v2_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://www.portalfiscal.inf.br/nfe&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:include schemaLocation=&quot;leiauteCancNFe_v2.00.xsd&quot;/&gt;
        ///	&lt;xs:element name=&quot;retCancNFe&quot; type=&quot;TRetCancNFe&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Schema XML de validação do retorno Pedido de Cancelamento [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string retCancNFe_v2_00 {
            get {
                return ResourceManager.GetString("retCancNFe_v2_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://www.portalfiscal.inf.br/nfe&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:include schemaLocation=&quot;leiauteConsultaCadastro_v2.00.xsd&quot;/&gt;
        ///	&lt;xs:element name=&quot;retConsCad&quot; type=&quot;TRetConsCad&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Schema XML de validação do retorno da consulta c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string retConsCad_v2_00 {
            get {
                return ResourceManager.GetString("retConsCad_v2_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://www.portalfiscal.inf.br/nfe&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:include schemaLocation=&quot;leiauteNFe_v2.00.xsd&quot;/&gt;
        ///	&lt;xs:element name=&quot;retConsReciNFe&quot; type=&quot;TRetConsReciNFe&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Schema XML de validação do retorno do Pedido de  Cons [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string retConsReciNFe_v2_00 {
            get {
                return ResourceManager.GetString("retConsReciNFe_v2_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://www.portalfiscal.inf.br/nfe&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:include schemaLocation=&quot;leiauteConsSitNFe_v2.00.xsd&quot;/&gt;
        ///	&lt;xs:element name=&quot;retConsSitNFe&quot; type=&quot;TRetConsSitNFe&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Schema XML de validação do retorno da consulta d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string retConsSitNFe_v2_00 {
            get {
                return ResourceManager.GetString("retConsSitNFe_v2_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://www.portalfiscal.inf.br/nfe&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:include schemaLocation=&quot;leiauteConsStatServ_v2.00.xsd&quot;/&gt;
        ///	&lt;xs:element name=&quot;retConsStatServ&quot; type=&quot;TRetConsStatServ&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Schema XML de validação do Resultado da Co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string retConsStatServ_v2_00 {
            get {
                return ResourceManager.GetString("retConsStatServ_v2_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://www.portalfiscal.inf.br/nfe&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:include schemaLocation=&quot;leiauteNFe_v2.00.xsd&quot;/&gt;
        ///	&lt;xs:element name=&quot;retEnviNFe&quot; type=&quot;TRetEnviNFe&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Schema XML de validação do retorno do Pedido de Concessão de  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string retEnviNFe_v2_00 {
            get {
                return ResourceManager.GetString("retEnviNFe_v2_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://www.portalfiscal.inf.br/nfe&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:include schemaLocation=&quot;leiauteInutNFe_v2.00.xsd&quot;/&gt;
        ///	&lt;xs:element name=&quot;retInutNFe&quot; type=&quot;TRetInutNFe&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Schema XML de validação do retorno do Pedido de Inutiliza [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string retInutNFe_v2_00 {
            get {
                return ResourceManager.GetString("retInutNFe_v2_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- PL_006h - 13/05/11 - correções da NT 2011/004  // v2.0--&gt;
        ///&lt;!-- PL_006f - 29/05/10 - correcao do tipo TDec_1504 para limitar a quantidade de decimais para 4  // v2.0--&gt;
        ///&lt;!-- PL_006f - 09/05/10 - eliminação da possibilidade informar a Inscrição produtor rural na IEDest  // v2.0--&gt;
        ///&lt;!-- PL_006d - 04/10/09 - alterada a ordem do pattern do TIE - adequacao libxml  // v2.0--&gt;
        ///&lt;!-- PL_006d - 20/08/09 - acrescentado o tipo númerico com 10 casas decimais,15 casas intei [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tiposBasico_v1_03 {
            get {
                return ResourceManager.GetString("tiposBasico_v1_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- ***************************************************--&gt;
        ///&lt;!-- ***   Schema específico para assinaturas XML    ***--&gt;
        ///&lt;!-- *** a partir de certificados do padrão (X509)   ***--&gt;
        ///&lt;!-- *** ICP-Brasil - Projeto Nota Fiscal Eletrônica ***--&gt;
        ///&lt;!-- ***************************************************--&gt;
        ///&lt;!-- Schema for XML Signatures--&gt;
        ///&lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; targetNamespace=&quot;http://www.w3.org/20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xmldsig_core_schema_v1_01 {
            get {
                return ResourceManager.GetString("xmldsig_core_schema_v1_01", resourceCulture);
            }
        }
    }
}
