//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nfebox.domain.tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nfebox.domain.tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;nfeProc versao=&quot;2.00&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot;&gt;
        ///  &lt;NFe xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot;&gt;
        ///    &lt;infNFe Id=&quot;NFe24110604385909000166550010000000521001535245&quot; versao=&quot;2.00&quot;&gt;
        ///      &lt;ide&gt;
        ///        &lt;cUF&gt;24&lt;/cUF&gt;
        ///        &lt;cNF&gt;00153524&lt;/cNF&gt;
        ///        &lt;natOp&gt;5929&lt;/natOp&gt;
        ///        &lt;indPag&gt;1&lt;/indPag&gt;
        ///        &lt;mod&gt;55&lt;/mod&gt;
        ///        &lt;serie&gt;1&lt;/serie&gt;
        ///        &lt;nNF&gt;52&lt;/nNF&gt;
        ///        &lt;dEmi&gt;2011-06-15&lt;/dEmi&gt;
        ///        &lt;dSaiEnt&gt;2011-06-15&lt;/dSaiEnt&gt;
        ///        &lt;hSaiEnt&gt;12:00:00&lt;/hSaiEnt&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NFe24110604385909000166550010000000521001535245 {
            get {
                return ResourceManager.GetString("NFe24110604385909000166550010000000521001535245", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;nfeProc versao=&quot;2.00&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot;&gt;
        ///  &lt;NFe xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot;&gt;
        ///    &lt;infNFe Id=&quot;NFe24110604385909000166550010000000531001542290&quot; versao=&quot;2.00&quot;&gt;
        ///      &lt;ide&gt;
        ///        &lt;cUF&gt;24&lt;/cUF&gt;
        ///        &lt;cNF&gt;00154229&lt;/cNF&gt;
        ///        &lt;natOp&gt;5929&lt;/natOp&gt;
        ///        &lt;indPag&gt;1&lt;/indPag&gt;
        ///        &lt;mod&gt;55&lt;/mod&gt;
        ///        &lt;serie&gt;1&lt;/serie&gt;
        ///        &lt;nNF&gt;53&lt;/nNF&gt;
        ///        &lt;dEmi&gt;2011-06-15&lt;/dEmi&gt;
        ///        &lt;tpNF&gt;1&lt;/tpNF&gt;
        ///        &lt;cMunFG&gt;2404200&lt;/cMunFG&gt;
        ///        &lt;tpImp&gt;1&lt;/tpImp&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NFe24110604385909000166550010000000531001542290 {
            get {
                return ResourceManager.GetString("NFe24110604385909000166550010000000531001542290", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;nfeProc versao=&quot;2.00&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot;&gt;&lt;NFe xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot;&gt;&lt;infNFe Id=&quot;NFe24111208403578000109550010000415051001727279&quot; versao=&quot;2.00&quot;&gt;&lt;ide&gt;&lt;cUF&gt;24&lt;/cUF&gt;&lt;cNF&gt;00172727&lt;/cNF&gt;&lt;natOp&gt;6102&lt;/natOp&gt;&lt;indPag&gt;1&lt;/indPag&gt;&lt;mod&gt;55&lt;/mod&gt;&lt;serie&gt;1&lt;/serie&gt;&lt;nNF&gt;41505&lt;/nNF&gt;&lt;dEmi&gt;2011-12-08&lt;/dEmi&gt;&lt;dSaiEnt&gt;2011-12-08&lt;/dSaiEnt&gt;&lt;hSaiEnt&gt;12:00:00&lt;/hSaiEnt&gt;&lt;tpNF&gt;1&lt;/tpNF&gt;&lt;cMunFG&gt;2408102&lt;/cMunFG&gt;&lt;tpImp&gt;1&lt;/tpImp&gt;&lt;tpEmis&gt;1&lt;/tpEmis&gt;&lt;cDV&gt;9&lt;/cDV&gt;&lt;tpAmb&gt;2&lt;/tpAmb&gt;&lt;finNFe&gt;1&lt;/finNFe&gt;&lt;procEm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NFe24111208403578000109550010000415051001727279 {
            get {
                return ResourceManager.GetString("NFe24111208403578000109550010000415051001727279", resourceCulture);
            }
        }
    }
}
